source:
  type: nats
  stream: LOGS
  consumer: pipeline
nodes:
  - id: parse
    type: extract
    field: body
    pattern: '^(?<words>(\w+\s?)*)$'
  - id: out
    type: sink.nats
    stream: PROCESSED
    subject: processed.logs
