acks: [ack, ack, ack]
sinks:
  out:
    - payload: {severity_text: ERROR, attributes: {duration_ms: 20}}
    - payload: {severity_text: INFO, attributes: {duration_ms: 3000}}
    - payload: {severity_text: ERROR, attributes: {duration_ms: 3000}}
    - payload: {severity_text: ERROR, attributes: {duration_ms: 3000}}
