[package]
name = "fusion-otel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fusion-core.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
thiserror.workspace = true

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["testing"] }

[lints]
workspace = true
