source:
  type: nats
  stream: LOGS
  consumer: pipeline
nodes:
  - id: keep_disk
    type: filter
    condition: 'body =~ "disk ("'
    action: keep
  - id: out
    type: sink.nats
    stream: PROCESSED
    subject: processed.logs
